services:
  manga-reader:
    container_name: manga-reader
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - /home/ivan/projects/manga-reader/.env
    command: flask db upgrade