services:
  manga-reader:
    container_name: manga-reader
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - /home/ivan/projects/manga-reader/.env
    volumes:
      - /var/storage/uploads/:./app/static/
      - /var/logs/manga-reader/:./app/logs/