services:
  manga-reader:
    container_name: manga-reader
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URI=${DATABASE_URI}