"""empty message

Revision ID: 2d66d4a2e43d
Revises: 57306406078d
Create Date: 2025-03-28 17:58:53.310810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d66d4a2e43d'
down_revision = '57306406078d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manga_background')
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('manga_background',
    sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('filename', name='manga_background_pkey')
    )
    # ### end Alembic commands ###
