"""empty message

Revision ID: 35a6ecdca1e0
Revises: 5860ae2b7a2a
Create Date: 2025-07-10 20:51:19.978534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a6ecdca1e0'
down_revision = '5860ae2b7a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_save',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('list_id', 'user_id')
    )
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_constraint('list_creator_id_key', type_='unique')
        batch_op.drop_constraint('list_name_key', type_='unique')

    with op.batch_alter_table('list_manga', schema=None) as batch_op:
        batch_op.drop_constraint('list_manga_manga_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('list_manga_list_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'manga', ['manga_id'], ['id'])
        batch_op.create_foreign_key(None, 'list', ['list_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_manga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('list_manga_list_id_fkey', 'manga', ['list_id'], ['id'])
        batch_op.create_foreign_key('list_manga_manga_id_fkey', 'list', ['manga_id'], ['id'])

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.create_unique_constraint('list_name_key', ['name'])
        batch_op.create_unique_constraint('list_creator_id_key', ['creator_id'])

    op.drop_table('list_save')
    # ### end Alembic commands ###
