"""empty message

Revision ID: 3b4b350c6a0b
Revises: 35a6ecdca1e0
Create Date: 2025-07-13 21:02:46.113539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4b350c6a0b'
down_revision = '35a6ecdca1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_poster_file', schema=None) as batch_op:
        batch_op.drop_constraint('manga_poster_file_poster_uuid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'manga_poster', ['poster_uuid'], ['uuid'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_poster_file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('manga_poster_file_poster_uuid_fkey', 'manga_poster', ['poster_uuid'], ['uuid'])

    # ### end Alembic commands ###
