"""empty message

Revision ID: 464b1e9f70d9
Revises: 5bc3f2474cff
Create Date: 2025-06-20 19:13:08.452805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '464b1e9f70d9'
down_revision = '5bc3f2474cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga_poster_file',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('poster_uuid', sa.String(), nullable=False),
    sa.Column('ext', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poster_uuid'], ['manga_poster.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_table('person')
    op.drop_table('subscriber')
    with op.batch_alter_table('manga_artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('manga_artist_person_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('person_id')

    with op.batch_alter_table('manga_author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('manga_author_person_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('person_id')

    with op.batch_alter_table('manga_poster', schema=None) as batch_op:
        batch_op.drop_column('filenames')

    with op.batch_alter_table('manga_publisher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('manga_publisher_person_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_publisher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('manga_publisher_person_id_fkey', 'person', ['person_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('manga_poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filenames', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))

    with op.batch_alter_table('manga_author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('manga_author_person_id_fkey', 'person', ['person_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('manga_artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('manga_artist_person_id_fkey', 'person', ['person_id'], ['id'])
        batch_op.drop_column('user_id')

    op.create_table('subscriber',
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='subscriber_person_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='subscriber_user_id_fkey')
    )
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name='person_creator_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='person_pkey')
    )
    op.drop_table('manga_poster_file')
    # ### end Alembic commands ###
