"""empty message

Revision ID: 50efc48d92fc
Revises: e511461b9279
Create Date: 2025-03-14 19:42:32.344327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50efc48d92fc'
down_revision = 'e511461b9279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga_background',
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.PrimaryKeyConstraint('filename')
    )
    op.create_table('manga_poster',
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.PrimaryKeyConstraint('filename')
    )
    op.drop_table('name_translation')
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_poster_number', sa.Integer(), nullable=True))
        batch_op.drop_column('poster')

    with op.batch_alter_table('manga_name_translation', schema=None) as batch_op:
        batch_op.alter_column('manga_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_name_translation', schema=None) as batch_op:
        batch_op.alter_column('manga_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('main_poster_number')

    op.create_table('name_translation',
    sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lang', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], name='name_translation_manga_id_fkey'),
    sa.PrimaryKeyConstraint('manga_id', 'lang', name='name_translation_pkey')
    )
    op.drop_table('manga_poster')
    op.drop_table('manga_background')
    # ### end Alembic commands ###
