"""empty message

Revision ID: 517357266fa4
Revises: 238182f0522c
Create Date: 2025-05-06 23:33:56.427594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517357266fa4'
down_revision = '238182f0522c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translation_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('chapter_manga_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('chapter_team_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'translation', ['translation_id'], ['id'])
        batch_op.drop_column('team_id')
        batch_op.drop_column('manga_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chapter_team_id_fkey', 'team', ['team_id'], ['id'])
        batch_op.create_foreign_key('chapter_manga_id_fkey', 'manga', ['manga_id'], ['id'])
        batch_op.drop_column('translation_id')

    op.drop_table('translation')
    # ### end Alembic commands ###
