"""empty message

Revision ID: 57306406078d
Revises: 4f2484f44f5f
Create Date: 2025-03-25 22:57:35.982472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57306406078d'
down_revision = '4f2484f44f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_poster', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('filenames',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.alter_column('filenames',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
