"""empty message

Revision ID: 5860ae2b7a2a
Revises: 8f068a6d8f40
Create Date: 2025-07-10 00:13:02.777473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5860ae2b7a2a'
down_revision = '8f068a6d8f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('list_manga',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('list_id', 'manga_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_manga')
    op.drop_table('list')
    # ### end Alembic commands ###
