"""empty message

Revision ID: 78019db2d85e
Revises: b0ef0ce6caa0
Create Date: 2025-07-03 19:04:50.717792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78019db2d85e'
down_revision = 'b0ef0ce6caa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
