"""empty message

Revision ID: 83bd47280003
Revises: ddf2942bcbae
Create Date: 2025-03-13 23:42:33.046355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83bd47280003'
down_revision = 'ddf2942bcbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adult',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adult_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('views',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'adult', ['adult_id'], ['id'])
        batch_op.drop_column('adult')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adult', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('views',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('verified')
        batch_op.drop_column('adult_id')

    op.drop_table('adult')
    # ### end Alembic commands ###
