"""empty message

Revision ID: a6888d358cb0
Revises: d2a80d7351d4
Create Date: 2025-03-25 22:51:48.828744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6888d358cb0'
down_revision = 'd2a80d7351d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('filenames', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
        batch_op.drop_constraint('manga_poster_manga_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'manga', ['manga_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('manga_poster_manga_id_fkey', 'manga', ['manga_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('filenames')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
