"""empty message

Revision ID: b91b4911e841
Revises: 3b4b350c6a0b
Create Date: 2025-07-17 17:04:15.199131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91b4911e841'
down_revision = '3b4b350c6a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_poster_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orig_filename', sa.String(), nullable=True))

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orig_filename', sa.String(), nullable=True))

    with op.batch_alter_table('team_poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orig_filename', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_poster', schema=None) as batch_op:
        batch_op.drop_column('orig_filename')

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_column('orig_filename')

    with op.batch_alter_table('manga_poster_file', schema=None) as batch_op:
        batch_op.drop_column('orig_filename')

    # ### end Alembic commands ###
