"""empty message

Revision ID: d12e4adcbb09
Revises: 
Create Date: 2025-03-21 17:35:39.648145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12e4adcbb09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_poster', schema=None) as batch_op:
        batch_op.drop_constraint('manga_poster_manga_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'manga', ['manga_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_poster', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('manga_poster_manga_id_fkey', 'manga', ['manga_id'], ['id'])

    # ### end Alembic commands ###
