"""empty message

Revision ID: d2a80d7351d4
Revises: 2793c51db83c
Create Date: 2025-03-25 22:49:42.452685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2a80d7351d4'
down_revision = '2793c51db83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('filenames', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
        batch_op.drop_constraint('manga_poster_manga_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'manga', ['manga_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('manga_poster_manga_id_fkey', 'manga', ['manga_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('filenames')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
