"""empty message

Revision ID: e511461b9279
Revises: 83bd47280003
Create Date: 2025-03-14 19:34:16.748142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e511461b9279'
down_revision = '83bd47280003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manga_wrapper')
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('manga_wrapper',
    sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('filename', name='manga_wrapper_pkey')
    )
    # ### end Alembic commands ###
