"""empty message

Revision ID: fc78f638d058
Revises: 8c7d904af5be
Create Date: 2025-06-08 19:18:57.889510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc78f638d058'
down_revision = '8c7d904af5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_comment',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('chapter_id', 'comment_id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('entity_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')

    op.drop_table('chapter_comment')
    # ### end Alembic commands ###
