"""empty message

Revision ID: ff94fd9d8b6a
Revises: 464b1e9f70d9
Create Date: 2025-06-20 19:14:52.846978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff94fd9d8b6a'
down_revision = '464b1e9f70d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga_poster_file',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('poster_uuid', sa.String(), nullable=False),
    sa.Column('ext', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poster_uuid'], ['manga_poster.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_table('subscriber')
    with op.batch_alter_table('manga_artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('person_id')

    with op.batch_alter_table('manga_author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('person_id')

    with op.batch_alter_table('manga_poster', schema=None) as batch_op:
        batch_op.drop_column('filenames')

    with op.batch_alter_table('manga_publisher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_publisher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('manga_poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filenames', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))

    with op.batch_alter_table('manga_author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('manga_artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('subscriber',
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='subscriber_user_id_fkey')
    )
    op.drop_table('manga_poster_file')
    # ### end Alembic commands ###
